### ISSUE TITLE
Prevent layout from styling tags that another layout component is responsible for

### ISSUE THREAD

**Issue by emma-alexandria** [pngwn/MDsveX#502]
I implemented a very simple dropcap through this code within my \<p> Svelte component:
```css
p:first-of-type::first-letter {
    font-size: 3rem;
    margin: 0.1em 0 0 0;
    padding: 0 0.1em 0 0;
    height: 0.7em;
    line-height: 0.7em;
    float: left;
    color: #990000;
  }
```
The problem I'm having is that because paragraph styling is applied to every \<p> tag, this also leads to the first letter of blockquotes becoming a dropcap (as they are also technically the first child of a parent)

I tried using `unset:all` within my blockquote component to remove css styling, but this doesn't apply to \<p> tags within the \<slot/>. I started working on some hacky fix involving an invisible \<slot/> that I would read the inner text from and then reconstruct \<p> tags to create my blockquotes, but I thought I should come here first to ask if there's any easy way to prevent this. 

Any help would be greatly appreciated!
